# Generated by Django 4.2.26 on 2025-11-21 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('paypal', 'PayPal'), ('coinbase', 'Coinbase Commerce')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=20)),
                ('provider_payment_id', models.CharField(blank=True, max_length=120)),
                ('provider_session_id', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MXN', max_length=10)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
