# Generated by Django 4.2.26 on 2025-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomQuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, help_text='Ej. ferreter\x1da, petroqu\x1cmica, log\x1bstica', max_length=150)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('current_challenge', models.TextField(help_text='Describe el problema principal que quieres resolver')),
                ('desired_outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('meeting_type', models.CharField(choices=[('remote', 'Remota'), ('on_site', 'En sitio')], default='remote', max_length=20)),
                ('preferred_date', models.DateField(blank=True, null=True)),
                ('preferred_time_range', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
