# Generated by Django 4.2.26 on 2025-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title_es', models.CharField(max_length=200)),
                ('title_en', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('problem_es', models.TextField()),
                ('problem_en', models.TextField(blank=True)),
                ('solution_es', models.TextField()),
                ('solution_en', models.TextField(blank=True)),
                ('impact_es', models.TextField(help_text='Resultados concretos, ej. -15% paros no programados')),
                ('impact_en', models.TextField(blank=True)),
                ('highlight_metric', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
