# Generated by Django 4.2.26 on 2025-12-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_default_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='URL-safe identifier, e.g. reporte-estadistico', unique=True)),
                ('name_es', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, max_length=120)),
                ('short_description_es', models.CharField(max_length=255)),
                ('short_description_en', models.CharField(blank=True, max_length=255)),
                ('description_es', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier for UI', max_length=50)),
                ('price_mxn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Individual Service',
                'verbose_name_plural': 'Individual Services',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
