# Generated by Django 4.2.26 on 2025-11-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role_es', models.CharField(max_length=150)),
                ('role_en', models.CharField(blank=True, max_length=150)),
                ('bio_es', models.TextField()),
                ('bio_en', models.TextField(blank=True)),
                ('avatar_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
